### ISSUE TITLE
About the data.

### ISSUE THREAD

**Issue by EdenGabriel** [water-cookie/citynav#2]
Hi, guys,
Thanks for your interesting work. Can you provide some examples about the rgbd data, such as `birmingham_block_0.png` `birmingham_block_0.tiff`(after processing by cloudcompare). I want to ensure the rightness of the preprocessed data.
Thank you very much.

**Comment by EdenGabriel** [comment]
Is there any additional operation when exporting depth data (.tif)?  such as, set the empty cells using `leave empty`? or other strategies?

**Comment by EdenGabriel** [comment]
Can u give the url of the web-based 3D flight simulator?

**Comment by miyatai2** [comment]
https://www.dropbox.com/scl/fi/hbj4mra1wpedjd5vzjq8b/rgbd.zip?rlkey=5miuvjyn83zf5e5lu4y0w834r&dl=0

**Comment by enjoysport2022** [comment]
Have you solved this problem? I am encountering the same issue. Thank you so much!

**Comment by enjoysport2022** [comment]
> https://www.dropbox.com/scl/fi/hbj4mra1wpedjd5vzjq8b/rgbd.zip?rlkey=5miuvjyn83zf5e5lu4y0w834r&dl=0
This link is not accessible.
